export const SYNTHETIC_DATASET_SUMMARY = {
  profileCount: 1600,
  csvRowsWithHeader: 1601,
  uniqueProfiles: 1600,
  blockingErrors: 0,
  outOfRangeGrades: 0,
  invalidBacSeries: 0,
  admissionRuleFailures: 0,
  ambiguousProfileRate: 21.6,
  generalistProfileRate: 33.1,
  maxGenderParityGap: 10.0,
  sourceJsonl: "Data/Dataset-synthétique/orientationDatasetProfile/data/ispm_orientation_dataset.jsonl",
  sourceCsv: "Data/Dataset-synthétique/orientationDatasetProfile/data/ispm_orientation_dataset.csv",
  validationReport: "Data/Dataset-synthétique/orientationDatasetProfile/reports/dataset_validation_report.txt",
  classDistribution: [
    { code: "IGGLIA", count: 160, percentage: 10.0 },
    { code: "ISAIA", count: 128, percentage: 8.0 },
    { code: "CAA", count: 127, percentage: 7.9 },
    { code: "FIC", count: 114, percentage: 7.1 },
    { code: "GCA", count: 111, percentage: 6.9 },
    { code: "IMTICIA", count: 109, percentage: 6.8 },
    { code: "EMII", count: 102, percentage: 6.4 },
    { code: "EMP", count: 101, percentage: 6.3 },
    { code: "TEH", count: 99, percentage: 6.2 },
    { code: "IAA", count: 93, percentage: 5.8 },
    { code: "ESIIA", count: 90, percentage: 5.6 },
    { code: "DTJA", count: 86, percentage: 5.4 },
    { code: "AEE", count: 77, percentage: 4.8 },
    { code: "PIP", count: 76, percentage: 4.8 },
    { code: "ICMP", count: 67, percentage: 4.2 },
    { code: "TEE", count: 60, percentage: 3.8 },
  ],
  validationChecks: [
    { label: "Unicité des profil_id", value: "1600/1600 uniques", status: "OK" },
    { label: "Notes hors bornes [0,20]", value: "0 valeur", status: "OK" },
    { label: "Champs listes trop courts / vides", value: "0", status: "OK" },
    { label: "Séries de bac hors référentiel", value: "0", status: "OK" },
    { label: "Cohérence moyenne recalculée", value: "0 écart", status: "OK" },
    { label: "Conditions d'admission ISPM non respectées", value: "0", status: "OK" },
    { label: "Contrôle anti-biais sexe/parcours", value: "Écart max 10 points", status: "OK" },
  ],
};
